version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: --httpPort=8080
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
